export const craneBeamWorkbookMap = {
  workbookFileName: 'подбор прокатной подкрановой балки v2.0.xlsx',
  sheets: {
    summary: 'Сводка',
    calculation: 'Расчет',
    auxiliary: 'Вспомогательная',
  },
  summaryInputs: {
    loadCapacityT: 'B1',
    craneSpanM: 'B2',
    wheelLoadKn: 'B3',
    wheelCount: 'B4',
    trolleyMassT: 'B5',
    craneBaseMm: 'B6',
    craneGaugeMm: 'B7',
    suspensionType: 'B8',
    dutyGroup: 'B9',
    craneCountInSpan: 'B11',
    craneRail: 'B13',
    railFootWidthM: 'B14',
    railHeightM: 'B15',
    beamSpanM: 'B17',
    brakeStructure: 'B18',
    stiffenerStepM: 'B19',
    tbnKn: 'B21',
    qbnKn: 'B22',
  },
  summaryDerived: {
    loadFactor: 'B24',
    gammaDGeneral: 'B25',
    gammaLocal: 'B26',
    fatigueNvyn: 'B27',
    alpha: 'B29',
    gammaC: 'B30',
    caseForTwoCranes: 'B34',
    designMxGeneral: 'B68',
    designMyGeneral: 'B69',
    designQGeneral: 'B70',
    designMtLocal: 'D71',
    designQAdditional: 'B72',
    maxUtilizationPercent: 'C84',
    selectedProfile: 'B85',
    totalWeightKg: 'B86',
  },
  calculationDerived: {
    selectedProfile: 'B14',
    selectedWeightKg: 'B15',
    selectedStiffenerStepM: 'B16',
    selectedUtilizationPercent: 'C14',
  },
} as const
